-- ============================================================================
-- Script de creation des donnees de test (utilisee par les Tests unitaires)
-- ============================================================================

-- --------------------------------------------------------------------------
-- Table HANGARS (numero, localisation, nombre_emplacements)
-- ----------------------------------------------------------------------------
INSERT INTO HANGARS VALUES(1, 'Alderaan', 12500);
INSERT INTO HANGARS VALUES(2, 'Arrakis', 12256);
INSERT INTO HANGARS VALUES(3, 'Corellia', 11000); 
INSERT INTO HANGARS VALUES(4, 'Coruscant', 12240); 
INSERT INTO HANGARS VALUES(5, 'Endor', 4900);
INSERT INTO HANGARS VALUES(6, 'Etoile noire', 120);
INSERT INTO HANGARS VALUES(7, 'Hoth', 7200);
INSERT INTO HANGARS VALUES(8, 'Mustafar', 4200);
INSERT INTO HANGARS VALUES(9, 'Naboo', 12120);
INSERT INTO HANGARS VALUES(10, 'Tatooine', 10465);

-- ----------------------------------------------------------------------------
-- Table VAISSEAUX & VAISSEAUX_INTER_GALACTIQUE
-- (id, modele, immatriculation, nombre_passager_max, capacite_fret (en tonnes), vitesse (en km/h), autonomie (en jours), id_hangar)
-- (id, multiplicateur_hyperdrive)
-- informations glanée sur internet a partir du JDR D6 StarWars (http://rpggamer.org)
-- ----------------------------------------------------------------------------
INSERT INTO VAISSEAUX VALUES(1, 'Cargo YT-1300', 'Flying Bird', 6, 100, 800, 60, 2);
INSERT INTO VAISSEAUX_INTER_GALACTIQUE VALUES (1, 2); -- Hyperpropulsion
INSERT INTO VAISSEAUX VALUES(2, 'Cargo YT-1300', 'Faucon Millenium', 6, 100, 1200, 60, 1);
INSERT INTO VAISSEAUX_INTER_GALACTIQUE VALUES (2, 0.5); -- Hyperpropulsion
INSERT INTO VAISSEAUX VALUES(3, 'T-65 X-Wings', 'Red Leader', 0, 0.11, 1050, 7, 1);
INSERT INTO VAISSEAUX_INTER_GALACTIQUE VALUES (3, 1); -- Hyperpropulsion
INSERT INTO VAISSEAUX VALUES(4, 'T-65 X-Wings', 'Red Two', 0, 0.11, 1050, 7, 1);
INSERT INTO VAISSEAUX_INTER_GALACTIQUE VALUES (4, 1); -- Hyperpropulsion
INSERT INTO VAISSEAUX VALUES(5, 'T-65 X-Wings', 'Red Three', 0, 0.11, 1050, 7, 1);
INSERT INTO VAISSEAUX_INTER_GALACTIQUE VALUES (5, 1); -- Hyperpropulsion
INSERT INTO VAISSEAUX VALUES(6, 'T-65 X-Wings', 'Red Four', 0, 0.11, 1050, 7, 1);
INSERT INTO VAISSEAUX_INTER_GALACTIQUE VALUES (6, 1); -- Hyperpropulsion

INSERT INTO VAISSEAUX VALUES(20, 'Tie Advanced', 'Dark Vador''s Tie Advanced', 0, 0.075, 1250, 2, 6);
INSERT INTO VAISSEAUX VALUES(21, 'Tie fighter', 'DS-61-2 (Mauler Mithel)', 0, 0.065, 1200, 2, 6);
INSERT INTO VAISSEAUX VALUES(22, 'Tie fighter', 'DS-61-3 (Backstabber)', 0, 0.065, 1200, 2, 6);
INSERT INTO VAISSEAUX VALUES(23, 'Tie fighter', 'DS-61-4 (Dark Curse)', 0, 0.065, 1200, 2, 6);

INSERT INTO VAISSEAUX VALUES(40, 'Firefly', 'Serenity', 8, 20000, 950, 365, 10);
INSERT INTO VAISSEAUX_INTER_GALACTIQUE VALUES (40, 2); -- Hyperpropulsion

INSERT INTO VAISSEAUX VALUES(50, 'Vipers Mark II', 'N7242C', 0, 0, 1000, 7, null);
INSERT INTO VAISSEAUX VALUES(51, 'Vipers Mark II', '1104NC', 0, 0, 1000, 7, null);
INSERT INTO VAISSEAUX VALUES(52, 'Vipers Mark VII', '8757NC', 0, 0, 1200, 7, null);
INSERT INTO VAISSEAUX VALUES(53, 'Raptor', 'Raptor 312', 10, 0.1, 1050, 14, null);
INSERT INTO VAISSEAUX_INTER_GALACTIQUE VALUES (53, 3); -- FTL
INSERT INTO VAISSEAUX VALUES(54, 'Furtive Viper', 'Blackbird', 0, 0, 1350, 7, null);
INSERT INTO VAISSEAUX_INTER_GALACTIQUE VALUES (54, 3); -- FTL
INSERT INTO VAISSEAUX VALUES(55, 'Battlestar (BS-75)', 'Galactica', 100, 50000, 850, 1800, null); -- 5 ans
INSERT INTO VAISSEAUX_INTER_GALACTIQUE VALUES (55, 3); -- FTL

INSERT INTO VAISSEAUX VALUES(70, 'Warship Glorious Heritage Class', 'Andromeda Ascendant', 500, 2500, 1050, 1450, 9); -- 4 ans
INSERT INTO VAISSEAUX_INTER_GALACTIQUE VALUES (70, 1); -- Slipstream
INSERT INTO VAISSEAUX VALUES(71, 'Slipstream-capable cargo ship', 'Eureka Maru', 10, 5300, 1000, 180, 9); -- 6 mois
INSERT INTO VAISSEAUX_INTER_GALACTIQUE VALUES (71, 2); -- Slipstream

INSERT INTO VAISSEAUX VALUES(90, 'Courrier classe Archange', 'Raphaël', 3, 0, 1200, 1800, 3); -- 5 ans
INSERT INTO VAISSEAUX_INTER_GALACTIQUE VALUES (90, 0); -- Gédéon

-- ----------------------------------------------------------------------------
-- Table EMPLOYES (matricule, type, nom, date_embauche, heures_vol)
-- ----------------------------------------------------------------------------
INSERT INTO EMPLOYES VALUES(1, 'PILOTE', 'Han Solo', '1977-06-09', 542);
INSERT INTO EMPLOYES VALUES(2, 'MECANICIEN', 'Chewbacca', '1977-06-09', null);
INSERT INTO EMPLOYES VALUES(3, 'PILOTE', 'Lando Calrissian', '1980-08-20', 228);
INSERT INTO EMPLOYES VALUES(4, 'PILOTE', 'Luke Skywalker', '1977-06-09', 649);
INSERT INTO EMPLOYES VALUES(5, 'MECANICIEN', 'D2-R2', '1977-06-09', null);
INSERT INTO EMPLOYES VALUES(6, 'MECANICIEN', 'C-3PO', '1977-06-09', null);
INSERT INTO EMPLOYES VALUES(7, 'PILOTE', 'Wedge Antilles', '1977-06-09', 549); -- Pilote XWing
INSERT INTO EMPLOYES VALUES(8, 'PILOTE', 'Derek Klivian', '1980-08-20', 567);-- Pilote XWing
INSERT INTO EMPLOYES VALUES(9, 'PILOTE', 'Biggs Darklighter', '1980-08-20', 573); -- Pilote XWing
INSERT INTO EMPLOYES VALUES(10, 'PILOTE', 'Tycho Celchu', '1980-08-20', 582);-- pilote XWing

INSERT INTO EMPLOYES VALUES(11, 'PILOTE', 'Dark Vador', '1977-06-09', 1289);
INSERT INTO EMPLOYES VALUES(12, 'PILOTE', 'Mauler Mithel', '1977-06-09', 989);
INSERT INTO EMPLOYES VALUES(13, 'PILOTE', 'Baron Soontir Fel', '1977-06-09', 743);
INSERT INTO EMPLOYES VALUES(14, 'PILOTE', 'Backstabber', '1977-06-09', 723);
INSERT INTO EMPLOYES VALUES(15, 'PILOTE', 'Dark Curse', '1977-06-09', 738);

INSERT INTO EMPLOYES VALUES(16, 'PILOTE', 'Malcolm "Mal" Reynolds', '2002-09-20', 687);
INSERT INTO EMPLOYES VALUES(17, 'PILOTE', 'Zoë Alleyne', '2002-09-20', 237);
INSERT INTO EMPLOYES VALUES(18, 'MECANICIEN', 'Jayne Cobb', '2002-09-20', null);
INSERT INTO EMPLOYES VALUES(19, 'PILOTE', 'Hoban "Wash" Washburne', '2002-09-20', 265);
INSERT INTO EMPLOYES VALUES(20, 'MECANICIEN', 'Kaywinnet Lee "Kaylee" Frye', '2002-09-20', null);

INSERT INTO EMPLOYES VALUES(21, 'PILOTE', 'William Adama', '2004-10-18', 1532);
INSERT INTO EMPLOYES VALUES(22, 'PILOTE', 'Saul Tigh', '2004-10-18', 1456);
INSERT INTO EMPLOYES VALUES(23, 'PILOTE', 'Lee "Apollo" Adama', '2004-10-18', 476);
INSERT INTO EMPLOYES VALUES(24, 'PILOTE', 'Louanne "Kat" Katraine', '2004-10-18', 296);
INSERT INTO EMPLOYES VALUES(25, 'PILOTE', 'Brendan "Hot Dog" Constanza', '2004-10-18', 327);
INSERT INTO EMPLOYES VALUES(26, 'PILOTE', 'Kara "Starbuck" Thrace', '2004-10-18', 887);
INSERT INTO EMPLOYES VALUES(27, 'PILOTE', 'Sharon "Boomer" Valerii', '2004-10-18', 582);
INSERT INTO EMPLOYES VALUES(28, 'MECANICIEN', 'Karl C. "Helo" Agathon', '2004-10-18', null);
INSERT INTO EMPLOYES VALUES(29, 'MECANICIEN', 'Galen Tyrol', '2004-10-18', null);

INSERT INTO EMPLOYES VALUES(30, 'PILOTE', 'Capitaine Dylan Hunt', '2000-10-02', 945);
INSERT INTO EMPLOYES VALUES(31, 'PILOTE', 'Rebeka "Beka" Valentine', '2000-10-02', 1374);
INSERT INTO EMPLOYES VALUES(32, 'PILOTE', 'Telemachus Rhade', '2003-09-29', 362);
INSERT INTO EMPLOYES VALUES(33, 'PILOTE', 'Rommie', '2000-10-02', 2548);
INSERT INTO EMPLOYES VALUES(34, 'MECANICIEN', 'Seamus Zelazny Harper', '2000-10-02', null);
INSERT INTO EMPLOYES VALUES(35, 'MECANICIEN', 'Trance Gemini', '2000-10-02', null);

INSERT INTO EMPLOYES VALUES(36, 'PILOTE', 'Père-capitaine Federico de Soya', '1995-01-1', 436);
INSERT INTO EMPLOYES VALUES(37, 'MECANICIEN', 'Le Gritche', '1989-01-01', null);

INSERT INTO EMPLOYES VALUES(38, 'PILOTE', 'Adam Reith', '1968-01-1', 754); -- non affecté

-- ----------------------------------------------------------------------------
-- Table AFFECTATION_EMPLOYES_VAISSEAUX
-- ----------------------------------------------------------------------------
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(1, 2);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(2, 2);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(3, 2);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(4, 3);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(5, 2);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(5, 3);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(6, 2);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(7, 4);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(9, 5);

INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(11, 20);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(12, 21);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(13, 22);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(14, 23);

INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(16, 40);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(17, 40);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(18, 40);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(19, 40);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(20, 40);

INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(21, 55);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(22, 55);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(23, 52);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(24, 50);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(25, 51);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(26, 54);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(27, 53);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(28, 53);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(29, 50);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(29, 51);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(29, 52);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(29, 53);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(29, 54);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(29, 55);

INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(30, 70);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(31, 71);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(32, 70);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(33, 70);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(34, 70);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(34, 71);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(35, 71);

INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(36, 90);
INSERT INTO AFFECTATION_EMPLOYES_VAISSEAUX VALUES(37, 90);

-- ----------------------------------------------------------------------------
-- Table AFFECTATION_MECANICIENS_SPECIALITES
-- ----------------------------------------------------------------------------
-- Chewbacca: Moteur, Armement, Blindage
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(2, 1);
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(2, 3);
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(2, 4);
-- D2-R2: Moteur, Hyperpropulsion, Electronique
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(5, 1);
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(5, 2);
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(5, 5);
-- C-3PO: Electronique
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(6, 5);
-- Jayne Cobb: Armement
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(16, 3);
-- Kaywinnet Lee "Kaylee" Frye: Moteur, Hyperpropulsion, Blindage, Electronique
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(18, 1);
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(18, 2);
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(18, 4);
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(18, 5);
-- Karl C. "Helo" Agathon: Electronique
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(26, 5);
-- Galen Tyrol: Moteur, Hyperpropulsion, Armement, Blindage, Electronique
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(27, 1);
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(27, 2);
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(27, 3);
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(27, 4);
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(27, 5);
-- Seamus Zelazny Harper: Moteur, Hyperpropulsion, Armement, Blindage, Electronique
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(32, 1);
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(32, 2);
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(32, 3);
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(32, 4);
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(32, 5);
-- Trance Gemini: 
-- Le Gritche: Armement, Blindage
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(35, 3);
INSERT INTO AFFECTATION_MECANICIENS_SPECIALITES VALUES(35, 4);

-- ----------------------------------------------------------------------------
-- Validation traitement
-- ----------------------------------------------------------------------------
COMMIT;
