-- ============================================================================
-- Script de creation des tables de l'application
-- ============================================================================

-- ----------------------------------------------------------------------------
-- suppression de l'existant
-- ----------------------------------------------------------------------------
DROP TABLE AFFECTATION_MECANICIENS_SPECIALITES IF EXISTS;
DROP TABLE AFFECTATION_EMPLOYES_VAISSEAUX IF EXISTS;
DROP TABLE EMPLOYES IF EXISTS;
DROP TABLE VAISSEAUX_INTER_GALACTIQUE IF EXISTS;
DROP TABLE VAISSEAUX IF EXISTS;
DROP TABLE HANGARS IF EXISTS;

DROP TABLE MECANICIENS_SPECIALITES IF EXISTS;

-- ----------------------------------------------------------------------------
-- Creation des tables de reference
-- ----------------------------------------------------------------------------
CREATE TABLE MECANICIENS_SPECIALITES (
	id BIGINT PRIMARY KEY,
	nom VARCHAR(20) UNIQUE
);

-- ----------------------------------------------------------------------------
-- Creation des tables
-- ----------------------------------------------------------------------------
CREATE TABLE HANGARS (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	localisation VARCHAR(50) NOT NULL,
	nombre_emplacements INT NOT NULL
);

CREATE TABLE EMPLOYES (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	type_employe VARCHAR(16) NOT NULL,
	nom VARCHAR(50) NOT NULL,
	date_embauche DATE,
	heures_vol INT
);

CREATE TABLE VAISSEAUX (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	modele VARCHAR(50) NOT NULL,
	immatriculation VARCHAR(50) NOT NULL,
	nombre_passager_max SMALLINT NOT NULL, 
	capacite_fret BIGINT NOT NULL,
	vitesse_atmospherique INT NOT NULL,
	autonomie INT NOT NULL,
	id_hangar BIGINT,
	CONSTRAINT BK_VAISSEAUX UNIQUE (immatriculation),
	CONSTRAINT FK_VAISSEAUX_HANGARS FOREIGN KEY (id_hangar) REFERENCES HANGARS (id)
);
COMMENT ON COLUMN VAISSEAUX.capacite_fret IS 'exprimée en tonnes';
COMMENT ON COLUMN VAISSEAUX.vitesse_atmospherique IS 'exprimée en km/h';
COMMENT ON COLUMN VAISSEAUX.autonomie IS 'exprimée en jours';

CREATE TABLE VAISSEAUX_INTER_GALACTIQUE (
	id BIGINT PRIMARY KEY,
	multiplicateur_hyperdrive SMALLINT NOT NULL,
	CONSTRAINT FK_VAISSEAUX_INTER_GALACTIQUE_VAISSEAUX FOREIGN KEY (ID) REFERENCES VAISSEAUX (ID)
);

-- Pas de liens de Vaisseaux vers employe : cascade des opérations par la base.
CREATE TABLE AFFECTATION_EMPLOYES_VAISSEAUX (
	id_employe BIGINT,
	id_vaisseau BIGINT,
	CONSTRAINT FK_AFFECTATION_EMPLOYES_VAISSEAUX_EMPLOYES FOREIGN KEY (id_employe) REFERENCES EMPLOYES (id),
	CONSTRAINT FK_AFFECTATION_EMPLOYES_VAISSEAUX_VAISSEAUX FOREIGN KEY (id_vaisseau) REFERENCES VAISSEAUX (id) MATCH SIMPLE ON DELETE CASCADE
);

CREATE TABLE AFFECTATION_MECANICIENS_SPECIALITES (
	id_employe BIGINT,
	id_specialite BIGINT,
	CONSTRAINT FK_AFFECTATION_MECANICIENS_SPECIALITES_EMPLOYES FOREIGN KEY (id_employe) REFERENCES EMPLOYES (id),
	CONSTRAINT FK_AFFECTATION_MECANICIENS_SPECIALITES_SPECIALITES FOREIGN KEY (id_specialite) REFERENCES MECANICIENS_SPECIALITES (id)
);


-- ----------------------------------------------------------------------------
-- Validation traitement
-- ----------------------------------------------------------------------------
COMMIT;
