-- ============================================================================
-- Script de creation des tables de l'application
-- ============================================================================

-- ----------------------------------------------------------------------------
-- suppression de l'existant
-- ----------------------------------------------------------------------------
DROP TABLE VAISSEAUX_INTER_GALACTIQUE IF EXISTS;
DROP TABLE VAISSEAUX IF EXISTS;
DROP TABLE HANGARS IF EXISTS;

-- ----------------------------------------------------------------------------
-- Creation des tables
-- ----------------------------------------------------------------------------
CREATE TABLE HANGARS (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	localisation VARCHAR(50) NOT NULL,
	nombre_emplacements INT NOT NULL
);

CREATE TABLE VAISSEAUX (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	modele VARCHAR(50) NOT NULL,
	immatriculation VARCHAR(50) NOT NULL,
	nombre_passager_max SMALLINT NOT NULL, 
	capacite_fret BIGINT NOT NULL,
	vitesse_atmospherique INT NOT NULL,
	autonomie INT NOT NULL,
	id_hangar BIGINT,
	CONSTRAINT BK_VAISSEAUX UNIQUE (immatriculation),
	CONSTRAINT FK_VAISSEAUX_HANGARS FOREIGN KEY (id_hangar) REFERENCES HANGARS (id)
);
COMMENT ON COLUMN VAISSEAUX.capacite_fret IS 'exprimée en tonnes';
COMMENT ON COLUMN VAISSEAUX.vitesse_atmospherique IS 'exprimée en km/h';
COMMENT ON COLUMN VAISSEAUX.autonomie IS 'exprimée en jours';

CREATE TABLE VAISSEAUX_INTER_GALACTIQUE (
	id BIGINT PRIMARY KEY,
	multiplicateur_hyperdrive SMALLINT NOT NULL,
	CONSTRAINT FK_VAISSEAUX_INTER_GALACTIQUE_VAISSEAUX FOREIGN KEY (ID) REFERENCES VAISSEAUX (ID)
);

-- ----------------------------------------------------------------------------
-- Validation traitement
-- ----------------------------------------------------------------------------
COMMIT;
